- id: '1527775836810'
  alias: open_curtain
  trigger:
  - entity_id: switch.curtain_on
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:00:12
  - data:
      entity_id: switch.curtain_on
    service: switch.turn_off
- id: '1527776274595'
  alias: close_curtain
  trigger:
  - entity_id: switch.curtain_off
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:00:12
  - data:
      entity_id: switch.curtain_off
    service: switch.turn_off
- id: '1527843957091'
  alias: welcome!
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.curtain_off
    service: switch.turn_on
- id: '1527844303854'
  alias: goodbye
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.curtain_on
    service: switch.turn_on
- id: '1528439939399'
  alias: door_dip
  trigger:
  - entity_id: switch.door_open
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:00:01
  - data:
      entity_id: switch.door_open
    service: switch.turn_off
- id: '1528556898770'
  alias: lifesuggest
  trigger:
  - entity_id: automation.door_dip
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: 07:00:00
    before: 09:00:00
    condition: time
  action:
  - data_template:
      message: 今天{{ states.sensor.suggestion_flu.state}}感冒，{{ states.sensor.suggestion_flu.attributes["建议"]
        }}，此外今天{{ states.sensor.suggestion_uv.attributes["建议"] }}，Home Assistant 祝您生活愉快
    service: tts.baidu_say

