- alias: face_indentify
  trigger:
  - entity_id: image_processing.facerec
    platform: numeric_state
    above: 0
  action:
  - service: tts.baidu_say
    data_template:
      message: "{% if states.image_processing.facerec.attributes.faces %}\n  {% if\
        \ states.image_processing.facerec.state | int == 1 %}\n    {{ states.image_processing.facerec.attributes[\"\
        faces\"][0][\"name\"] }} ，你好呀！\n  {% else %}\n    {% set my_test_json = states.image_processing.facerec.attributes.faces\
        \ %}\n    {% for i in range(0, my_test_json | length) %}\n    是你啊！{{my_test_json[i][\"\
        name\"]}}\n    {% endfor %}\n    你们好！\n  {% endif %}\n{% else %}\n  欢迎回来！\n\
        {% endif %}\n"
  id: df56444f9e164283a83e29bc51650042
- id: '1527775836810'
  alias: open_curtain
  trigger:
  - entity_id: switch.curtain_on
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:00:12
  - data:
      entity_id: switch.curtain_on
    service: switch.turn_off
- id: '1527776274595'
  alias: close_curtain
  trigger:
  - entity_id: switch.curtain_off
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:00:12
  - data:
      entity_id: switch.curtain_off
    service: switch.turn_off
- id: '1527781029843'
  alias: lifesuggestion
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001b1bbaf
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - above: '0'
    condition: numeric_state
    entity_id: image_processing.facerec
  - after: sunset
    condition: sun
  action:
  - data:
      message: '{{ states.sensor.suggestion.attributes["建议"] }}'
    service: tts.baidu_say
- id: '1527843957091'
  alias: welcome!
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001b1bbaf
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: sunrise
    condition: sun
  action:
  - data:
      entity_id: switch.curtain_off
    service: switch.turn_on
- id: '1527844303854'
  alias: goodbye
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.curtain_on
    service: switch.turn_on
